/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author david
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ConexionSQL;
import java.util.logging.Level;
import java.util.logging.Logger;
import controlador.DocenteControlador; // Importa tu controlador
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

public class docente extends javax.swing.JFrame {

    private DocenteControlador controller;

    /**
     * Creates new form docente
     */
    public docente() {
        initComponents();
        this.controller = new DocenteControlador(this);
        controller.deshabilitarCamposFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        botonregre = new javax.swing.JButton();
        lb_empleado = new javax.swing.JLabel();
        lb_nombre = new javax.swing.JLabel();
        lb_ApPat = new javax.swing.JLabel();
        lb_ApMat = new javax.swing.JLabel();
        lb_Correo = new javax.swing.JLabel();
        txtEmpleado = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnAnadir = new javax.swing.JButton();
        discardBtn = new javax.swing.JButton();
        BGUARDAR = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 57, 143));

        botonregre.setBackground(new java.awt.Color(51, 51, 255));
        botonregre.setForeground(new java.awt.Color(51, 51, 255));
        botonregre.setIcon(new javax.swing.ImageIcon("D:\\alexv\\Downloads\\flecha3.png")); // NOI18N
        botonregre.setText("Atras");
        botonregre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonregreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(botonregre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 721, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonregre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 50));

        lb_empleado.setText("No. empleado");
        getContentPane().add(lb_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 74, 80, -1));

        lb_nombre.setText("Nombre");
        getContentPane().add(lb_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 110, 50, 20));

        lb_ApPat.setText("Apellido paterno");
        getContentPane().add(lb_ApPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 150, 90, -1));

        lb_ApMat.setText("Apellido materno");
        getContentPane().add(lb_ApMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 190, -1, -1));

        lb_Correo.setText("Correo");
        getContentPane().add(lb_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 230, 40, -1));
        getContentPane().add(txtEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 430, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 430, -1));
        getContentPane().add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 430, -1));
        getContentPane().add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 430, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 430, -1));

        btnAnadir.setText("Añadir");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        discardBtn.setText("Descartar");
        discardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardBtnActionPerformed(evt);
            }
        });
        getContentPane().add(discardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        BGUARDAR.setBackground(new java.awt.Color(0, 176, 80));
        BGUARDAR.setText("Guardar");
        BGUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGUARDARActionPerformed(evt);
            }
        });
        getContentPane().add(BGUARDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonregreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonregreActionPerformed
        controller.regresarVentana();

    }//GEN-LAST:event_botonregreActionPerformed

    private void BGUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGUARDARActionPerformed
        controller.guardarDocente();
    }//GEN-LAST:event_BGUARDARActionPerformed

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        controller.habilitarCamposFormulario();
        controller.limpiarCamposFormulario();
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void discardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardBtnActionPerformed
        controller.limpiarCamposFormulario();
        controller.deshabilitarCamposFormulario();
    }//GEN-LAST:event_discardBtnActionPerformed

   



    


    public JTextField getTxtEmpleado() {
        return txtEmpleado;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public JTextField getTxtApellidoP() {
        return txtApellidoP;
    }

    public JTextField getTxtApellidoM() {
        return txtApellidoM;
    }

    public JTextField getTxtCorreo() {
        return txtCorreo;
    }

    public JButton getBGUARDAR() {
        return BGUARDAR;
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BGUARDAR;
    private javax.swing.JButton botonregre;
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton discardBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb_ApMat;
    private javax.swing.JLabel lb_ApPat;
    private javax.swing.JLabel lb_Correo;
    private javax.swing.JLabel lb_empleado;
    private javax.swing.JLabel lb_nombre;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEmpleado;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
