/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author carlo
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        btnEstudianteMenu = new javax.swing.JButton();
        btnDocenteMenu = new javax.swing.JButton();
        btnBancoProyecto = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        panelSubEstudiante = new javax.swing.JPanel();
        btnNuevaLista = new javax.swing.JButton();
        btnEditarLista = new javax.swing.JButton();
        panelSubDocente = new javax.swing.JPanel();
        btnRegistrarDocente = new javax.swing.JButton();
        btnEditarDocente = new javax.swing.JButton();
        lblEstudiante = new javax.swing.JLabel();
        lblDocente = new javax.swing.JLabel();
        lblProyectos = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        btnCentroEstudiante = new javax.swing.JButton();
        btnCentroBanco = new javax.swing.JButton();
        btnCentroDocente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(226, 226, 226));

        panelMenu.setBackground(new java.awt.Color(0, 32, 96));

        btnEstudianteMenu.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnEstudianteMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnEstudianteMenu.setText("Estudiante");
        btnEstudianteMenu.setBorder(null);
        btnEstudianteMenu.setContentAreaFilled(false);

        btnDocenteMenu.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnDocenteMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnDocenteMenu.setText("Docente");
        btnDocenteMenu.setBorder(null);
        btnDocenteMenu.setContentAreaFilled(false);
        btnDocenteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocenteMenuActionPerformed(evt);
            }
        });

        btnBancoProyecto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnBancoProyecto.setForeground(new java.awt.Color(255, 255, 255));
        btnBancoProyecto.setText("Banco de proyecto");
        btnBancoProyecto.setBorder(null);
        btnBancoProyecto.setContentAreaFilled(false);

        btnSalir.setBackground(new java.awt.Color(255, 47, 47));
        btnSalir.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setOpaque(true);

        panelSubEstudiante.setBackground(new java.awt.Color(0, 32, 96));

        btnNuevaLista.setBackground(new java.awt.Color(0, 55, 164));
        btnNuevaLista.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnNuevaLista.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaLista.setText("Nueva lista");
        btnNuevaLista.setBorder(null);
        btnNuevaLista.setContentAreaFilled(false);
        btnNuevaLista.setOpaque(true);

        btnEditarLista.setBackground(new java.awt.Color(0, 55, 164));
        btnEditarLista.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnEditarLista.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarLista.setText("Editar lista");
        btnEditarLista.setBorder(null);
        btnEditarLista.setContentAreaFilled(false);
        btnEditarLista.setOpaque(true);

        javax.swing.GroupLayout panelSubEstudianteLayout = new javax.swing.GroupLayout(panelSubEstudiante);
        panelSubEstudiante.setLayout(panelSubEstudianteLayout);
        panelSubEstudianteLayout.setHorizontalGroup(
            panelSubEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSubEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevaLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelSubEstudianteLayout.setVerticalGroup(
            panelSubEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevaLista, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSubDocente.setBackground(new java.awt.Color(0, 32, 96));

        btnRegistrarDocente.setBackground(new java.awt.Color(0, 55, 164));
        btnRegistrarDocente.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnRegistrarDocente.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarDocente.setText("Registrar");
        btnRegistrarDocente.setBorder(null);
        btnRegistrarDocente.setContentAreaFilled(false);
        btnRegistrarDocente.setOpaque(true);

        btnEditarDocente.setBackground(new java.awt.Color(0, 55, 164));
        btnEditarDocente.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnEditarDocente.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarDocente.setText("Editar");
        btnEditarDocente.setBorder(null);
        btnEditarDocente.setContentAreaFilled(false);
        btnEditarDocente.setOpaque(true);

        javax.swing.GroupLayout panelSubDocenteLayout = new javax.swing.GroupLayout(panelSubDocente);
        panelSubDocente.setLayout(panelSubDocenteLayout);
        panelSubDocenteLayout.setHorizontalGroup(
            panelSubDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubDocenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSubDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelSubDocenteLayout.setVerticalGroup(
            panelSubDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubDocenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/birrete.png"))); // NOI18N

        lblDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/profesor-en-la-pizarra.png"))); // NOI18N
        lblDocente.setText("\n");

        lblProyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestion-de-proyectos.png"))); // NOI18N

        lblCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar-sesion.png"))); // NOI18N

        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu.png"))); // NOI18N

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstudiante)
                            .addComponent(lblDocente)
                            .addComponent(lblProyectos)
                            .addComponent(lblCerrarSesion))
                        .addGap(18, 18, 18)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnBancoProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(panelSubDocente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDocenteMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelSubEstudiante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEstudianteMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblMenu))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenu)
                .addGap(31, 31, 31)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEstudianteMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstudiante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSubEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDocenteMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDocente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSubDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBancoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProyectos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addComponent(lblCerrarSesion)
                        .addGap(15, 15, 15))))
        );

        jLabel6.setText("jLabel6");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/usuarioEditar.png"))); // NOI18N

        lblBienvenida.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(0, 0, 0));
        lblBienvenida.setText("Bienvenido UsuarioPrueba");

        btnCentroEstudiante.setBackground(new java.awt.Color(0, 32, 96));
        btnCentroEstudiante.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnCentroEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnCentroEstudiante.setText("Estudiante");
        btnCentroEstudiante.setBorder(null);
        btnCentroEstudiante.setContentAreaFilled(false);
        btnCentroEstudiante.setOpaque(true);

        btnCentroBanco.setBackground(new java.awt.Color(0, 32, 96));
        btnCentroBanco.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnCentroBanco.setForeground(new java.awt.Color(255, 255, 255));
        btnCentroBanco.setText("Banco de proyecto");
        btnCentroBanco.setBorder(null);
        btnCentroBanco.setContentAreaFilled(false);
        btnCentroBanco.setOpaque(true);

        btnCentroDocente.setBackground(new java.awt.Color(0, 32, 96));
        btnCentroDocente.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnCentroDocente.setForeground(new java.awt.Color(255, 255, 255));
        btnCentroDocente.setText("Docente");
        btnCentroDocente.setBorder(null);
        btnCentroDocente.setContentAreaFilled(false);
        btnCentroDocente.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCentroBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCentroEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCentroDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 48, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblBienvenida, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(124, 124, 124)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCentroDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCentroEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCentroBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDocenteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocenteMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDocenteMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBancoProyecto;
    public javax.swing.JButton btnCentroBanco;
    public javax.swing.JButton btnCentroDocente;
    public javax.swing.JButton btnCentroEstudiante;
    public javax.swing.JButton btnDocenteMenu;
    public javax.swing.JButton btnEditarDocente;
    public javax.swing.JButton btnEditarLista;
    public javax.swing.JButton btnEstudianteMenu;
    public javax.swing.JButton btnNuevaLista;
    public javax.swing.JButton btnRegistrarDocente;
    public javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblBienvenida;
    public javax.swing.JLabel lblCerrarSesion;
    public javax.swing.JLabel lblDocente;
    public javax.swing.JLabel lblEstudiante;
    public javax.swing.JLabel lblMenu;
    public javax.swing.JLabel lblProyectos;
    public javax.swing.JPanel panelMenu;
    public javax.swing.JPanel panelSubDocente;
    public javax.swing.JPanel panelSubEstudiante;
    // End of variables declaration//GEN-END:variables
}
