/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author carlo
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel6, "src/iconos/Logo-TecNM.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel1, "src/iconos/Logo3d TecNM.png");
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        btnEstudianteMenu = new javax.swing.JButton();
        btnDocenteMenu = new javax.swing.JButton();
        btnBancoProyecto = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        panelSubEstudiante = new javax.swing.JPanel();
        btnNuevaLista = new javax.swing.JButton();
        btnEditarLista = new javax.swing.JButton();
        panelSubDocente = new javax.swing.JPanel();
        btnRegistrarDocente = new javax.swing.JButton();
        lblEstudiante = new javax.swing.JLabel();
        lblDocente = new javax.swing.JLabel();
        lblProyectos = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblBienvenida = new javax.swing.JLabel();
        btnCentroEstudiante = new javax.swing.JButton();
        btnCentroBanco = new javax.swing.JButton();
        btnCentroDocente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(226, 226, 226));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(0, 32, 96));

        btnEstudianteMenu.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnEstudianteMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnEstudianteMenu.setText("Estudiante");
        btnEstudianteMenu.setBorder(null);
        btnEstudianteMenu.setContentAreaFilled(false);

        btnDocenteMenu.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnDocenteMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnDocenteMenu.setText("Docente");
        btnDocenteMenu.setBorder(null);
        btnDocenteMenu.setContentAreaFilled(false);
        btnDocenteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocenteMenuActionPerformed(evt);
            }
        });

        btnBancoProyecto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnBancoProyecto.setForeground(new java.awt.Color(255, 255, 255));
        btnBancoProyecto.setText("Banco de proyecto");
        btnBancoProyecto.setBorder(null);
        btnBancoProyecto.setContentAreaFilled(false);

        btnSalir.setBackground(new java.awt.Color(176, 0, 0));
        btnSalir.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setBorder(null);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setOpaque(true);

        panelSubEstudiante.setBackground(new java.awt.Color(0, 32, 96));

        btnNuevaLista.setBackground(new java.awt.Color(0, 38, 84));
        btnNuevaLista.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnNuevaLista.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaLista.setText("Nueva lista");
        btnNuevaLista.setBorder(null);
        btnNuevaLista.setContentAreaFilled(false);
        btnNuevaLista.setOpaque(true);

        btnEditarLista.setBackground(new java.awt.Color(0, 38, 84));
        btnEditarLista.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnEditarLista.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarLista.setText("Editar lista");
        btnEditarLista.setBorder(null);
        btnEditarLista.setContentAreaFilled(false);
        btnEditarLista.setOpaque(true);

        javax.swing.GroupLayout panelSubEstudianteLayout = new javax.swing.GroupLayout(panelSubEstudiante);
        panelSubEstudiante.setLayout(panelSubEstudianteLayout);
        panelSubEstudianteLayout.setHorizontalGroup(
            panelSubEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSubEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevaLista, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(btnEditarLista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelSubEstudianteLayout.setVerticalGroup(
            panelSubEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevaLista, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelSubDocente.setBackground(new java.awt.Color(0, 32, 96));

        btnRegistrarDocente.setBackground(new java.awt.Color(0, 38, 84));
        btnRegistrarDocente.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnRegistrarDocente.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarDocente.setText("Registrar");
        btnRegistrarDocente.setBorder(null);
        btnRegistrarDocente.setContentAreaFilled(false);
        btnRegistrarDocente.setOpaque(true);

        javax.swing.GroupLayout panelSubDocenteLayout = new javax.swing.GroupLayout(panelSubDocente);
        panelSubDocente.setLayout(panelSubDocenteLayout);
        panelSubDocenteLayout.setHorizontalGroup(
            panelSubDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubDocenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrarDocente, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelSubDocenteLayout.setVerticalGroup(
            panelSubDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubDocenteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        lblEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/birrete.png"))); // NOI18N

        lblDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/profesor-en-la-pizarra.png"))); // NOI18N
        lblDocente.setText("\n");

        lblProyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/gestion-de-proyectos.png"))); // NOI18N

        lblCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cerrar-sesion.png"))); // NOI18N

        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/menu.png"))); // NOI18N

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstudiante)
                            .addComponent(lblDocente)
                            .addComponent(lblProyectos)
                            .addComponent(lblCerrarSesion))
                        .addGap(18, 18, 18)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnBancoProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(panelSubDocente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDocenteMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelSubEstudiante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEstudianteMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblMenu))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenu)
                .addGap(31, 31, 31)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEstudianteMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstudiante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSubEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDocenteMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDocente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSubDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBancoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProyectos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addComponent(lblCerrarSesion)
                        .addGap(15, 15, 15))))
        );

        jPanel1.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 700));

        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 0, 220, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/usuarioEditar.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(956, 6, -1, -1));

        lblBienvenida.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(0, 0, 0));
        lblBienvenida.setText("Bienvenido UsuarioPrueba");
        jPanel1.add(lblBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(1006, 6, 210, 32));

        btnCentroEstudiante.setBackground(new java.awt.Color(0, 32, 96));
        btnCentroEstudiante.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnCentroEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnCentroEstudiante.setText("Estudiante");
        btnCentroEstudiante.setBorder(null);
        btnCentroEstudiante.setContentAreaFilled(false);
        btnCentroEstudiante.setOpaque(true);
        jPanel1.add(btnCentroEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 174, 400, 100));

        btnCentroBanco.setBackground(new java.awt.Color(0, 32, 96));
        btnCentroBanco.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnCentroBanco.setForeground(new java.awt.Color(255, 255, 255));
        btnCentroBanco.setText("Banco de proyecto");
        btnCentroBanco.setBorder(null);
        btnCentroBanco.setContentAreaFilled(false);
        btnCentroBanco.setOpaque(true);
        jPanel1.add(btnCentroBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 292, 400, 100));

        btnCentroDocente.setBackground(new java.awt.Color(0, 32, 96));
        btnCentroDocente.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        btnCentroDocente.setForeground(new java.awt.Color(255, 255, 255));
        btnCentroDocente.setText("Docente");
        btnCentroDocente.setBorder(null);
        btnCentroDocente.setContentAreaFilled(false);
        btnCentroDocente.setOpaque(true);
        jPanel1.add(btnCentroDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(804, 174, 400, 100));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 560, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDocenteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocenteMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDocenteMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBancoProyecto;
    public javax.swing.JButton btnCentroBanco;
    public javax.swing.JButton btnCentroDocente;
    public javax.swing.JButton btnCentroEstudiante;
    public javax.swing.JButton btnDocenteMenu;
    public javax.swing.JButton btnEditarLista;
    public javax.swing.JButton btnEstudianteMenu;
    public javax.swing.JButton btnNuevaLista;
    public javax.swing.JButton btnRegistrarDocente;
    public javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblBienvenida;
    public javax.swing.JLabel lblCerrarSesion;
    public javax.swing.JLabel lblDocente;
    public javax.swing.JLabel lblEstudiante;
    public javax.swing.JLabel lblMenu;
    public javax.swing.JLabel lblProyectos;
    public javax.swing.JPanel panelMenu;
    public javax.swing.JPanel panelSubDocente;
    public javax.swing.JPanel panelSubEstudiante;
    // End of variables declaration//GEN-END:variables
}
