/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author david
 */


public class VistaDocente extends javax.swing.JFrame {

    

    /**
     * Creates new form docente
     */
    public VistaDocente() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        botonregre = new javax.swing.JButton();
        lb_empleado = new javax.swing.JLabel();
        lb_nombre = new javax.swing.JLabel();
        lb_ApPat = new javax.swing.JLabel();
        lb_ApMat = new javax.swing.JLabel();
        lb_Correo = new javax.swing.JLabel();
        txtEmpleado = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        discardBtn = new javax.swing.JButton();
        BGUARDAR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lblerrorempleado = new javax.swing.JLabel();
        errornombre = new javax.swing.JLabel();
        errorapellidop = new javax.swing.JLabel();
        errorapellidom = new javax.swing.JLabel();
        errortelefono = new javax.swing.JLabel();
        errorcorreo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(35, 57, 143));

        botonregre.setBackground(new java.awt.Color(51, 51, 255));
        botonregre.setForeground(new java.awt.Color(255, 255, 255));
        botonregre.setText("Atras");
        botonregre.setContentAreaFilled(false);
        botonregre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonregreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(botonregre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 680, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonregre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 50));

        lb_empleado.setText("No. empleado");
        getContentPane().add(lb_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 74, 80, -1));

        lb_nombre.setText("Nombre");
        getContentPane().add(lb_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 110, 50, 20));

        lb_ApPat.setText("Apellido paterno");
        getContentPane().add(lb_ApPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 150, 90, -1));

        lb_ApMat.setText("Apellido materno");
        getContentPane().add(lb_ApMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 190, -1, -1));

        lb_Correo.setText("Correo");
        getContentPane().add(lb_Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 40, -1));
        getContentPane().add(txtEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 430, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 430, -1));
        getContentPane().add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 430, -1));
        getContentPane().add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 430, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 430, -1));

        discardBtn.setText("Descartar");
        discardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardBtnActionPerformed(evt);
            }
        });
        getContentPane().add(discardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        BGUARDAR.setBackground(new java.awt.Color(0, 176, 80));
        BGUARDAR.setForeground(new java.awt.Color(255, 255, 255));
        BGUARDAR.setText("Guardar");
        BGUARDAR.setContentAreaFilled(false);
        BGUARDAR.setOpaque(true);
        BGUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BGUARDARActionPerformed(evt);
            }
        });
        getContentPane().add(BGUARDAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));

        jLabel2.setText("Telefono");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 430, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 750, 170));

        lblerrorempleado.setForeground(new java.awt.Color(204, 0, 0));
        lblerrorempleado.setText("jLabel3");
        getContentPane().add(lblerrorempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));

        errornombre.setForeground(new java.awt.Color(204, 0, 0));
        errornombre.setText("jLabel4");
        getContentPane().add(errornombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        errorapellidop.setForeground(new java.awt.Color(204, 0, 0));
        errorapellidop.setText("jLabel5");
        getContentPane().add(errorapellidop, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        errorapellidom.setForeground(new java.awt.Color(204, 0, 0));
        errorapellidom.setText("jLabel6");
        getContentPane().add(errorapellidom, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        errortelefono.setForeground(new java.awt.Color(204, 0, 0));
        errortelefono.setText("jLabel7");
        getContentPane().add(errortelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        errorcorreo.setForeground(new java.awt.Color(204, 0, 0));
        errorcorreo.setText("jLabel8");
        getContentPane().add(errorcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonregreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonregreActionPerformed

    }//GEN-LAST:event_botonregreActionPerformed

    private void BGUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BGUARDARActionPerformed
    }//GEN-LAST:event_BGUARDARActionPerformed

    private void discardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardBtnActionPerformed

    }//GEN-LAST:event_discardBtnActionPerformed

   



    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BGUARDAR;
    public javax.swing.JButton botonregre;
    public javax.swing.JButton discardBtn;
    public javax.swing.JLabel errorapellidom;
    public javax.swing.JLabel errorapellidop;
    public javax.swing.JLabel errorcorreo;
    public javax.swing.JLabel errornombre;
    public javax.swing.JLabel errortelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    private javax.swing.JLabel lb_ApMat;
    private javax.swing.JLabel lb_ApPat;
    private javax.swing.JLabel lb_Correo;
    private javax.swing.JLabel lb_empleado;
    private javax.swing.JLabel lb_nombre;
    public javax.swing.JLabel lblerrorempleado;
    public javax.swing.JTextField txtApellidoM;
    public javax.swing.JTextField txtApellidoP;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtEmpleado;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
